### ISSUE TITLE
Premium Sponser tag obscures footer content

### ISSUE THREAD

**Issue by theNaut1lus** [adonisjs/legacy.adonisjs.com#36]
Just logging a quick here, when scrolling through the website i found that the premium contributors tag seems to be obscuring content on the page and on scrolling all the way down, it tends to sit over the footer and obscures the creator's name.

### Screenshot
![screenshot](https://user-images.githubusercontent.com/35738138/60258379-a6d51200-98f2-11e9-8a94-844b84e6b89a.png)

This could be fixed by adding some sort of a opacity filter to the banner or to shift it to some place else, would love to contribute on this and take up this issue 🥇

**Comment by RomainLanz** [comment]
Hey @co16353sidak! 👋 

Happy to accept a PR! 🤗

**Comment by theNaut1lus** [comment]
@RomainLanz 
Would love it if you could be give me a direction forward, I am unable to locate the styles for the concerned area. any help is much appreciated.

**Comment by annymosse** [comment]
@co16353sidak i think this is not an issue since you can remove it via the devTooland the whole framework moving to the next release version.
you can find it inside on of these templates files inside the following path https://github.com/adonisjs/adonisjs.com/blob/v4/resources/views/

**Update**
the related file and line is https://github.com/adonisjs/adonisjs.com/blob/dd96d5c5125606fdd9e42f2d16d5f2f2db1bd141/resources/views/partials/footer.edge#L23-L28
